# self-signed cert for gateway
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
spec:
  dnsNames:
  - gateway.tap-choice-bluebird.tapsandbox.com
  secretName: example-cert-tls
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gateway
spec:
  virtualhost:
    fqdn: gateway.tap-choice-bluebird.tapsandbox.com
    tls:
      secretName: example-cert-tls
  routes:
    - services:
        - name: gateway
          port: 80