apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway
  labels:
    gateway: gateway
spec:
  api:
    description: "Gateway for the apps"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: gateway-routes
spec:
  routes:
    - uri: https://httpbin.org
      predicates:
        - Path=/httpbin/get
      filters:
        - AddRequestHeader=X-Request-Extra, Hello HTTPBin from Spring Cloud Gateway!
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RemoveJsonAttributesResponseBody=groupId
        - AddResponseHeader=Content-Security-Policy, upgrade-insecure-requests
    - uri: http://app.developer-ns
      predicates:
        - Path=/app
      filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RemoveJsonAttributesResponseBody=groupId
        - AddResponseHeader=Content-Security-Policy, upgrade-insecure-requests
    - uri: http://scg-operator.tap-install
      predicates:
        - Path=/operator/openapi/{namespace}/{name}
      filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RemoveJsonAttributesResponseBody=groupId
        - AddResponseHeader=Content-Security-Policy, upgrade-insecure-requests

---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: gateway-mapping
spec:
  gatewayRef:
    name: gateway
  routeConfigRef:
    name: gateway-routes