apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app
spec:
  image: dsyer/app
  env:
    - name: SPRING_APPLICATION_JSON
      value: '{"management.endpoint.health.probes.add-additional-paths":"true","logging.level.org.springframework.web":"trace"}'
